Created button component  Issue #1
girlscript-blr/BuildWithGSBlr-Raahat pull request #18
Opened 2020-10-11 11:55 UTC by ShivangiRai1310

#1 Created button component, added the default prop values.
Tested the button component on App.js, have attached the pictures for the same.

Kindly review the PR and let me know anything that is to be changed.

![Screenshot (240)](https://user-images.githubusercontent.com/57129598/95677901-8d8ace80-0be6-11eb-8604-8827669ae499.png)

![Screenshot (237)](https://user-images.githubusercontent.com/57129598/95677861-3edd3480-0be6-11eb-80e2-57a22d5a4d18.png)

2020-10-11 15:06 UTC, smilegupta requested changes
Can you remove some extra commented code written in the  files.
Also if possible can you prettify the code once using prettifier ?

2020-10-11 15:06 UTC, smilegupta commented on src/components/common/button/button.js
> +    if( props.variant === "secondary")
can u remove this console.log statement

2020-10-11 15:06 UTC, smilegupta commented on src/components/common/button/button.js
> +*/
can u please remove the commented code

2020-10-12 09:16 UTC, ShivangiRai1310 commented
Done the changes:
1. Removed additional comments and console.log
2. Used Prettifier

2020-10-18 09:48 UTC, ShivangiRai1310 commented
Hii, @smilegupta could you please review the changes and merge it if there is no issue with the code.

2020-10-24 08:43 UTC, smilegupta approved these changes

2020-10-24 08:46 UTC, smilegupta commented
Greetings from Build With Girlscript Bangalore😃

Dear participant,

We have gone through your pull request made for the issue #18 
 
Congratulations🎊 🎉 on getting your pull request successfully merged into our application **Build with GSBlr-Raahat**. 

We will soon be distributing your valuable badge(s)🥇🥈🥉🎖️ corresponding to the pull requests that are merged. Please fill the [participation form](https://tinyurl.com/buildwithgsblr) 📃 to receive your badges, if not already done.

Also, [RSVP here](https://tinyurl.com/gsblr-hacktoberfest2020) here, if you haven't yet,  to get a chance to win a limited-edition Hacktoberfest 👕 T-shirt or a 🎍plant.

Learning is a never-ending process. 📈  We will be coming up with *new issues*, stay tuned. Meanwhile you can also check out our other [Code with GirlScript Bangalore Repository](https://github.com/girlscript-blr/code-with-girlscript-bangalore) to try some problem solving and earn exciting badges.

Thanks for your contribution! Happy coding😃

2020-10-24 08:47 UTC, merged

2020-10-24 09:40 UTC, girlscript-blr commented
Hi @ShivangiRai1310 

Please fill the [participation form](https://tinyurl.com/buildwithgsblr) 📃 to receive your badges.

Thanks